export const place = [
  {
    type: "Outdoor",
    name: "Monumen Nasional",
    desc: "Monumen Nasional atau yang disingkat dengan Monas atau Tugu Monas adalah monumen peringatan setinggi 132 meter (433 kaki) yang terletak tepat di tengah Lapangan Medan Merdeka, Jakarta Pusat.",
    todo: [
      "Bawa alas karena Anda dapat piknik disini.",
      "Anda dapat melihat museum yang ada di dalam Monas.",
      "Siapkan moment selfie terbaikmu.",
    ],
    fee: "20.000",
    latitude: -6.175392,
    longitude: 106.827194,
    imgUrl:
      "https://images.unsplash.com/photo-1635924201021-e8ae80c2bdc0?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=743&q=80",
  },
  {
    type: "Outdoor",
    name: "Kebun Raya Bogor",
    desc: "Sebuah kebun botani besar yang terletak di Kota Bogor, Indonesia. Kebun ini dioperasikan oleh Lembaga Ilmu Pengetahuan Indonesia (LIPI). Kebun ini terletak di pusat kota Bogor dan bersebelahan dengan kompleks istana kepresidenan Istana Bogor. Luasnya mencapai 87 hektar dan memiliki 15.000 jenis koleksi pohon dan tumbuhan. Letak geografis Bogor yang mengalami hujan hampir setiap hari bahkan di musim kemarau menjadikan kebun ini sebagai lokasi yang menguntungkan untuk budidaya tanaman tropis. ",
    todo: [
      "Disarankan bawa alas karena Anda dapat piknik disini.",
      "Disini terdapat banyak jenis tanaman, cocok untuk tempat bersantai dan menikmati udara sejuk dengan partner mu.",
      "Terdapat tempat penyewaan sepeda, untuk berkeliling Kebun Raya Bogor",
      "Dapat menjadi tempat berselfie-ria.",
    ],
    fee: "26.500",
    latitude: -6.597629,
    longitude: 106.799568,
    imgUrl:
      "https://images.unsplash.com/photo-1624154381283-eda340ee2ce1?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=627&q=80",
  },
  {
    type: "Outdoor",
    name: "Kota Tua",
    desc: "Kota tua di Jakarta, yang juga bernama Kota Tua, berpusat di Alun-Alun Fatahillah, yaitu alun-alun yang ramai dengan pertunjukan rutin tarian tradisional. Museum Sejarah Jakarta adalah bangunan era Belanda dengan lukisan dan barang antik, sedangkan Museum Wayang memamerkan boneka kayu khas Jawa. Desa Glodok, atau Chinatown, terkenal dengan makanan kaki lima, seperti pangsit dan mi goreng. Di dekatnya, terdapat sekunar dan kapal penangkap ikan di pelabuhan Sunda Kelapa yang kuno.",
    todo: [],
    fee: "5000",
    latitude: -6.1364489,
    longitude: 106.8130661,
    imgUrl:
      "https://images.unsplash.com/photo-1587053114035-e94f4162a358?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=735&q=80",
  },
  {
    type: "Outdoor",
    name: "Hutan Kota GBK",
    desc: "Area hijau dengan berbagai lapangan olahraga & stadion bisbol, plus restoran & area piknik.",
    todo: [],
    fee: "0",
    latitude: -6.2219727,
    longitude: 106.8076506,
    imgUrl: "https://img.beritasatu.com/investor/1636910930.jpg",
  },
  {
    type: "Outdoor",
    name: "Dunia Fantasi (Dufan)",
    desc: "Dufan atau disebut juga Dunia Fantasi adalah sebuah theme park yang terletak di kawasan Taman Impian Jaya Ancol, Jakarta Utara, Indonesia yang diresmikan dan dibuka untuk umum pada tanggal 29 Agustus 1985",
    todo: [],
    fee: "195.000",
    latitude: -6.1253124,
    longitude: 106.8335377,
    imgUrl:
      "https://s-light.tiket.photos/t/01E25EBZS3W0FY9GTG6C42E1SE/rsfit19201280gsm/events/2021/12/08/9c6ae660-1799-4276-b81d-f8b0b85669d6-1638949473006-1e6c55a1b1edca6bf250012af2cc79e2.jpg",
  },
  {
    type: "Outdoor",
    name: "Jungleland Adventure Theme Park",
    desc: "Taman Bertema Petualangan JungleLand! Terletak di lahan seluas 35 hektar di Bogor, tempat ini pasti akan membuat hari (atau minggu) Anda lebih cerah dengan lebih dari 33 jenis wahana dan atraksi yang cocok untuk segala usia. Apakah Anda siap untuk beberapa tantangan? Pacu adrenalin Anda di Mega Drop, coba Air Race, atau biarkan anak Anda 'terbang' dengan Magic Bike. ",
    todo: [],
    fee: "139.500",
    latitude: -6.5722214,
    longitude: 106.8947026,
    imgUrl:
      "https://s-light.tiket.photos/t/01E25EBZS3W0FY9GTG6C42E1SE/rsfit19201280gsm/events/2022/01/19/cadfcd5e-4589-4297-9e94-9c33923fc2a5-1642581784344-11c6d174b2ada8ada13fcad9a18a682a.jpg",
  },
  {
    type: "Outdoor",
    name: "Cimory Dailyland",
    desc: "Cimory Dairyland Puncak merupakan sebuah tempat wisata keluarga di kawasan Puncak, Bogor yang berkembang dibawah naungan perusahaan yoghurt terbesar di Indonesia yaitu Cimory.",
    todo: [],
    fee: "40.000",
    latitude: -6.6500882,
    longitude: 106.9027234,
    imgUrl:
      "https://www.len-diary.com/wp-content/uploads/2022/08/cimory-dairyland.jpg",
  },
  {
    type: "Outdoor",
    name: "Kebun Margasatwa Ragunan",
    desc: "Ragunan dikenal karena Kebun Binatang Ragunan, yaitu taman hutan hujan besar dengan pusat primata, gajah, dan harimau Sumatra, serta jalan setapak teduh yang populer di kalangan para pelari. Di dekatnya, terdapat Taman Anggrek Ragunan yang merupakan area terbuka hijau publik dengan taman anggrek. Pilihan bersantap di area ini meliputi gerai piza dan kedai ramen, serta tempat makan lokal bernuansa santai yang menyajikan nasi goreng kambing dan sambal lele. ",
    todo: [],
    fee: "4.000",
    latitude: -6.3119408,
    longitude: 106.8208153,
    imgUrl:
      "https://asset.kompas.com/crops/-CruCWJs9294lmHx5dHWYWBMkDQ=/0x30:640x457/750x500/data/photo/2022/05/03/6270d45ecf3ee.jpeg",
  },
  {
    type: "Outdoor",
    name: "Taman Lapangan Banteng",
    desc: "Lapangan Banteng, dulu bernama Waterlooplein (bahasa Belanda: plein = lapangan) yaitu suatu lapangan yang terletak di Weltevreden, Batavia; tidak jauh dari Gereja Katedral Jakarta. Pada masa itu, Lapangan Banteng dikenal dengan sebutan Lapangan Singa karena di tengahnya terpancang tugu peringatan kemenangan pertempuran di Waterloo, dengan patung singa di atasnya. Pertempuran Waterloo tersebut terjadi tanggal 18 Juni 1815 di dekat kota Waterloo, yaitu sekitar 15 km ke arah selatan dari ibu kota Belgia, Brussels. Pertempuran itu merupakan pertempuran terakhir Napoleon melawan pasukan gabungan Inggris-Belanda-Jerman. Pertempuran ini juga dicatat dalam sejarah sebagai penutup dari seratus hari sejak larinya Napoleon dari pengasingannya di pulau Elba.  ",
    todo: [],
    fee: "26.500",
    latitude: -6.170555,
    longitude: 106.8350378,
    imgUrl:
      "https://images.unsplash.com/photo-1575705810583-a0ceedc2d464?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NHx8bGFwcGFuZ2FuJTIwYmFudGVuZ3xlbnwwfHwwfHw%3D&auto=format&fit=crop&w=600&q=60",
  },
  {
    type: "Outdoor",
    name: "Cove at Batavia PIK",
    desc: "Cove Batavia PIK atau yang memiliki nama asli Cove at Batavia Pantai Indah Kapuk merupakan sebuah tempat hangout dan kulineran baru di seputar kawasan PIK 2. Didesain dengan konsep bangunan dan tata ruang ala Los Angeles, Amerika Serikat menjadikan tempat ini semakin menarik.",
    todo: [],
    fee: "0",
    latitude: -6.0888954,
    longitude: 106.7414316,
    imgUrl:
      "https://anekatempatwisata.com/wp-content/uploads/2022/04/Cove-at-Batavia-mbetch.jpg",
  },
  {
    type: "Outdoor",
    name: "Tebet Eco Park",
    desc: "Tebet Eco Park adalah sebuah taman yang terletak di Tebet, Jakarta Selatan, Jakarta, Indonesia. Taman tersebut memiliki luas tanah 7 hektare. Taman tersebut adalah tempat populer untuk hiburan, sosialisasi dan rekreasi untuk masyarakat sekitar.",
    todo: [],
    fee: "0",
    latitude: -6.2373489,
    longitude: 106.8529248,
    imgUrl:
      "https://asset.kompas.com/crops/l0s8yDEK0mTdeWefMntgm2_Ehng=/8x0:683x450/750x500/data/photo/2022/02/08/62022fea9a150.jpeg",
  },
  {
    type: "Indoor",
    name: "Museum M.A.C.A.N",
    desc: "The Museum of Modern and Contemporary Art in Nusantara (Museum Seni Modern dan Kontemporer di Nusantara) atau Museum MACAN adalah museum seni di Kebon Jeruk di Jakarta, Indonesia. Museum ini adalah yang pertama di Indonesia yang memiliki koleksi seni modern dan kontemporer Indonesia dan internasional. Museum ini memiliki luas lantai 7.107 meter persegi dengan area tampilan sekitar 4.000 meter persegi. Museum ini termasuk dalam daftar 100 Tempat Terbaik Dunia 2018 yang dirilis oleh majalah Time. Museum MACAN dibuka pada November 2017. ",
    todo: [
      "Anda dapat melihat banyak karya seni modern dan kontemporer dari Indonesia atau mancanegara.",
      "Dapat menjadi tempat foto bersama pasangan date-mu.",
    ],
    fee: "56.000",
    latitude: -6.1910434,
    longitude: 106.7679858,
    imgUrl:
      "https://s-light.tiket.photos/t/01E25EBZS3W0FY9GTG6C42E1SE/rsfit19201280gsm/events/2022/10/18/f14fa2eb-56a0-4e07-abdf-43a536defe25-1666068868562-470eab7454546274150dd55298b749d6.jpg",
  },
  {
    type: "Indoor",
    name: "Museum Nasional Indonesia",
    desc: "Museum Nasional Indonesia, atau yang sering disebut dengan Museum Gajah, adalah sebuah museum arkeologi, sejarah, etnografi, dan geografi yang terletak di Jakarta Pusat dan persisnya di Jalan Merdeka Barat 12. Museum ini merupakan museum pertama dan terbesar di Asia Tenggara. ",
    todo: [
      "Anda dapat melihat banyak karya seni di museum Gajah, banyak koleksi benda-benda kuno dari seluruh Nusantara. ",
      "Dapat menjadi tempat foto bersama pasangan date-mu.",
    ],
    fee: "15.000",
    latitude: -6.1763968,
    longitude: 106.8194014,
    imgUrl:
      "https://imgx.parapuan.co/crop/0x0:0x0/x/photo/2022/06/23/museum-nasional-jadi-hidden-gem-20220623104748.jpg",
  },
  {
    type: "Indoor",
    name: "Taman Ismail Marzuki",
    desc: "Pusat Kesenian Jakarta Taman Ismail Marzuki yang populer disebut Taman Ismail Marzuki merupakan sebuah pusat kesenian dan kebudayaan yang berlokasi di Jalan Cikini Raya 73, Jakarta Pusat. Di komplek TIM, berdiri juga Institut Kesenian Jakarta dan Planetarium Jakarta.",
    todo: [],
    fee: "15.000",
    latitude: -6.1891586,
    longitude: 106.8397738,
    imgUrl:
      "https://lh3.googleusercontent.com/p/AF1QipPlkQ5jBB4VD5Uy0PrzYtxvbxo-1HkFPyFxYVJp=s1360-w1360-h1020",
  },
  {
    type: "Indoor",
    name: "Museum MOJA",
    desc: "Moja Museum Jakarta merupakan salah satu museum yang iconic dan estetik untuk berfoto ria. Moja Museum menyediakan banyak sekali spot instagramable dengan warna berkonsep kekinian khas milenial dan generasi Z.",
    todo: [],
    fee: "115.000",
    latitude: -6.2175929,
    longitude: 106.8031745,
    imgUrl: "https://mycity.co.id/wp-content/uploads/2021/09/moja4.jpg",
  },

  {
    type: "Indoor",
    name: "Jakarta Aquarium Safari",
    desc: "Jakarta Aquarium & Safari, the largest indoor Living Planet in Indonesia, a signature of Taman Safari Indonesia in collaboration with Aquaria KLCC, Malaysia. ",
    todo: [],
    fee: "142.500",
    latitude: -6.174946,
    longitude: 106.7898091,
    imgUrl:
      "https://blue.kumparan.com/image/upload/fl_progressive,fl_lossy,c_fill,q_auto:best,w_640/v1634025439/01gar37wem6q19q1smfzpqyx57.jpg",
  },
  {
    type: "Indoor",
    name: "Pandora Horror Experience",
    desc: "Pandora Experience adalah Ultimate Escape Game Adventure dimana pemain akan memasuki setiap ruang permainan secara berkelompok hingga 10 orang. Sepanjang perjalanan yang mendebarkan, mereka akan menemukan kejutan, lorong rahasia, ruang tersembunyi, dan teka-teki yang membingungkan. Dengan bekerja sebagai tim, tujuannya adalah menyelesaikan semua tugas di dalam dalam waktu yang ditentukan. Tantangan dimulai!",
    todo: [],
    fee: "185.000",
    latitude: -6.1685311,
    longitude: 106.7868975,
    imgUrl:
      "https://cdn.antaranews.com/cache/800x533/2019/01/Screen-Shot-2019-01-01-at-21.29.20.png",
  },
  {
    type: "Indoor",
    name: "Galeri Nasional Indonesia",
    desc: "Galeri Nasional Indonesia adalah sebuah lembaga budaya negara atau sebagai museum seni rupa modern dan kontemporer. Di sini terdapat gedung yang berfungsi antara lain sebagai tempat pameran, dan perhelatan seni rupa Indonesia dan mancanegara.",
    todo: [],
    fee: "0",
    latitude: -6.1785482,
    longitude: 106.8327716,
    imgUrl:
      "http://kebudayaan.kemdikbud.go.id/galerinasional/wp-content/uploads/sites/10/2021/10/Foto-Dok.-GNI-Montiari-4-scaled.jpg",
  },
  {
    type: "Indoor",
    name: "Museum Taman Prasasti",
    desc: "Museum Taman Prasasti adalah sebuah museum cagar budaya peninggalan masa kolonial Belanda yang berada di Jalan Tanah Abang No. 1, Jakarta Pusat. Museum ini memiliki koleksi prasasti nisan kuno serta miniatur makam khas dari 27 provinsi di Indonesia, beserta koleksi kereta jenazah antik. ",
    todo: [],
    fee: "5.000",
    latitude: -6.172224,
    longitude: 106.8189695,
    imgUrl:
      "https://cdn2.tstatic.net/tribunnewswiki/foto/bank/images/mUSEUM-TAMAN-PRASASTI.jpg",
  },
  {
    type: "Indoor",
    name: "Monumen Pancasila Sakti",
    desc: "Monumen Pancasila Sakti dibangun atas gagasan Presiden ke-2 Indonesia, Soeharto. Dibangun di atas tanah seluas 14,6 hektare. Monumen ini dibangun dengan tujuan mengingat perjuangan para Pahlawan Revolusi yang berjuang mempertahankan ideologi negara Republik Indonesia, Pancasila dari ancaman ideologi komunis.",
    todo: [],
    fee: "5.000",
    latitude: -6.2903745,
    longitude: 106.9086168,
    imgUrl:
      "https://upload.wikimedia.org/wikipedia/commons/c/c5/Monumen_Pancasila_Sakti.jpg",
  },
  {
    type: "Indoor",
    name: "Museum Zoologi",
    desc: "Museum Zoologi Bogor adalah museum yang terletak di Bogor, memiliki koleksi yang berkaitan dengan dunia satwa seperti berbagai spesimen yang diawetkan maupun fosil hewan. Museum ini terbagi menjadi dua, salah satunya dibuka setiap hari untuk umum yang berisi ruang pameran terletak di Jalan Ir. H. Juanda No.",
    todo: [],
    fee: "15.000",
    latitude: -6.6036134,
    longitude: 106.7969367,
    imgUrl:
      "https://binaqurani.sch.id/wp-content/uploads/2022/05/Bina-Qurani-Museum-Zoologi-Bogor-Photo-by-GS-Image.jpg",
  },
  {
    type: "Culinary",
    name: "Kopi Nako Bogor",
    desc: "Makanan rumahan tradisional Indonesia & teh buah yang keren di kedai kopi kontemporer.",
    todo: [],
    fee: "",
    latitude: -6.6373951,
    longitude: 106.8649331,
    imgUrl:
      "https://tempat.com/blog/wp-content/uploads/2019/12/75631510_615501049194793_6357712646916566990_n-820x1024.jpg",
  },
  {
    type: "Culinary",
    name: "Sky Garden Cafe",
    desc: "Kafe trendi & kontemporer yang menawarkan pilihan menu Barat & Indonesia.",
    todo: [],
    fee: "",
    latitude: -6.2209294,
    longitude: 106.8292377,
    imgUrl:
      "https://media-cdn.tripadvisor.com/media/photo-s/0e/8a/8a/a8/sky-garden-cafe-with.jpg",
  },
  {
    type: "Culinary",
    name: "Kopi Daong",
    desc: "",
    todo: [],
    fee: "",
    latitude: -6.7248248,
    longitude: 106.8755887,
    imgUrl:
      "https://o-cdf.sirclocdn.com/unsafe/o-cdn-cas.sirclocdn.com/parenting/images/wisata-kopi-daong.width-800.jpegquality-80.jpg",
  },
  {
    type: "Culinary",
    name: "Warung Pasta",
    desc: "",
    todo: [],
    fee: "",
    latitude: -6.3587775,
    longitude: 106.8329752,
    imgUrl:
      "https://listyapratiwi.com/wp-content/uploads/2017/01/warung-pasta-depok.jpg",
  },
  {
    type: "Culinary",
    name: "Hello Summer Bogor",
    desc: "Sebuah cafe cantik dengan nuansa tropis ala Bali seperti taglinenya “Bali Vibes in Bogor”",
    todo: [],
    fee: "",
    latitude: -6.6174758,
    longitude: 106.8137691,
    imgUrl:
      "https://idnwisata.com/wp-content/uploads/2022/02/hello-summer-cafe.jpg",
  },
  {
    type: "Culinary",
    name: "Walking Drums Depok",
    desc: "",
    todo: [],
    fee: "",
    latitude: -6.3671109,
    longitude: 106.8342967,
    imgUrl:
      "https://image.archify.com/blog/l/06-Walking-Drums-Margonda-Ruang-Jeda-Ruang-Berkumpul.jpg",
  },
  {
    type: "Culinary",
    name: "Kataramen",
    desc: "Sebuah kedai ramen dengan rasa ramen signature ala Jepang yang telah hadir di Tebet, Jakarta Selatan",
    todo: [],
    fee: "",
    latitude: -6.2289787,
    longitude: 106.8561598,
    imgUrl:
      "https://wisatamilenial.com/wp-content/uploads/2022/06/Lokasi-Kataramen-Tebet-Image-From-@trip_or_treatss.jpg",
  },
];
